[workspace]
members = [
    "crates/*"
]

resolver = "2"

[workspace.package]
version = "0.0.1-alpha.4"
authors = ["Benedikt Schwab <benedikt.schwab@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/envis-space/erosbag"

[workspace.dependencies]
epoint = { version = "0.0.1-alpha.4" }
eimage = { version = "0.0.1-alpha.4" }
ecoord = { version = "0.0.1-alpha.4" }

clap = "4.5.13"
dotenvy = "0.15.7"
walkdir = "2.5.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
diesel = "~2.2.2"
diesel_migrations = "~2.2.0"
r2d2 = "0.8.10"
serde = "1.0.204"
serde_derive = "1.0.204"
serde_repr = "0.1.19"
serde_yaml = "0.9.34"
serde-big-array = "0.5.1"
cdr = "0.2.4"
thiserror = "1.0.63"
polars = "0.41.3"
ndarray = "0.16.0"
indextree = "4.7.0"
rayon = "1.10.0"
nalgebra = "0.33.0"
chrono = "0.4.38"
itertools = "0.13.0"
image = "0.25.2"
