[workspace]
members = [
    "crates/*"
]

[workspace.package]
version = "0.0.1-alpha.1"
authors = ["Benedikt Schwab"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/tum-gis/erosbag"

[workspace.dependencies]
epoint = { version = "0.0.1-alpha", registry = "custom" }
ecoord = { version = "0.0.1-alpha", registry = "custom" }

clap = "4.0.4"
dotenvy = "0.15.0"
walkdir = "2.3.2"
tracing = "0.1.30"
tracing-subscriber = "0.3.8"
diesel = "2.0.2"
diesel_migrations = "2.0.0"
serde = "1.0"
serde_derive = "1.0.143"
serde_repr = "0.1"
serde_yaml = "0.9"
serde-big-array = "0.4.1"
cdr = "0.2.4"
thiserror = "1.0.35"
polars = "0.26.1"
ndarray = "0.15.6"
indextree = "4.4.0"
rayon = "1.5.3"
nalgebra = "0.31.1"
chrono = "0.4.22"
itertools = "0.10.5"
